namespace Pr
{
    public partial class Currencies
    {
        public Aed Uyu { get; set; }
        public Aed Pyg { get; set; }
        public Aed Gmd { get; set; }
        public Aed Djf { get; set; }
        public Aed Eur { get; set; }
        public Aed Usd { get; set; }
        public Aed Gel { get; set; }
        public Aed Bzd { get; set; }
        public Aed Mur { get; set; }
        public Aed Lbp { get; set; }
        public Aed Sar { get; set; }
        public Aed Brl { get; set; }
        public Aed Ugx { get; set; }
        public Aed Qar { get; set; }
        public Aed Mnt { get; set; }
        public Aed Clp { get; set; }
        public Aed Lrd { get; set; }
        public Aed Aud { get; set; }
        public Aed Xcd { get; set; }
        public Aed Twd { get; set; }
        public Aed Ars { get; set; }
        public Aed Xof { get; set; }
        public Aed Dkk { get; set; }
        public Aed Fok { get; set; }
        public Aed Mad { get; set; }
        public Aed Mru { get; set; }
        public Aed Uah { get; set; }
        public Aed Cny { get; set; }
        public Aed Lsl { get; set; }
        public Aed Zar { get; set; }
        public Aed Cdf { get; set; }
        public Aed Rub { get; set; }
        public Aed Bdt { get; set; }
        public Aed Ang { get; set; }
        public Aed Gtq { get; set; }
        public Aed Ils { get; set; }
        public Aed Gyd { get; set; }
        public Aed Kyd { get; set; }
        public Aed Hrk { get; set; }
        public Aed Isk { get; set; }
        public Aed Nad { get; set; }
        public Aed Gip { get; set; }
        public Aed Omr { get; set; }
        public Aed Kwd { get; set; }
        public Aed Gbp { get; set; }
        public Aed Hnl { get; set; }
        public Aed Shp { get; set; }
        public Aed Khr { get; set; }
        public Aed Mkd { get; set; }
        public Aed Irr { get; set; }
        public Aed Pab { get; set; }
        public Aed Ckd { get; set; }
        public Aed Nzd { get; set; }
        public Aed Bif { get; set; }
        public Aed Ttd { get; set; }
        public Aed Kmf { get; set; }
        public Aed Ngn { get; set; }
        public Aed Pln { get; set; }
        public Aed Xpf { get; set; }
        public Aed Etb { get; set; }
        public Aed Azn { get; set; }
        public Aed Npr { get; set; }
        public Aed Bbd { get; set; }
        public Aed Jep { get; set; }
        public Aed Inr { get; set; }
        public Aed Kgs { get; set; }
        public Aed Ssp { get; set; }
        public Aed Iqd { get; set; }
        public Aed Cuc { get; set; }
        public Aed Cup { get; set; }
        public Aed Btn { get; set; }
        public Aed Bsd { get; set; }
        public Aed Nok { get; set; }
        public Aed Kes { get; set; }
        public Aed Sek { get; set; }
        public Aed Xaf { get; set; }
        public Aed Mop { get; set; }
        public Aed Ggp { get; set; }
        public Aed Rwf { get; set; }
        public Aed Syp { get; set; }
        public Aed Cad { get; set; }
        public Aed Dzd { get; set; }
        public Aed Imp { get; set; }
        public Aed Bwp { get; set; }
        public Aed Kzt { get; set; }
        public Aed Ves { get; set; }
        public Bam Sdg { get; set; }
        public Aed Sbd { get; set; }
        public Aed Jmd { get; set; }
        public Aed Afn { get; set; }
        public Aed Rsd { get; set; }
        public Aed Tjs { get; set; }
        public Aed Top { get; set; }
        public Aed Kid { get; set; }
        public Aed Ern { get; set; }
        public Aed Htg { get; set; }
        public Aed Vuv { get; set; }
        public Bam Bam { get; set; }
        public Aed Wst { get; set; }
        public Aed Bob { get; set; }
        public Aed Mga { get; set; }
        public Aed Stn { get; set; }
        public Aed Bhd { get; set; }
        public Aed Pen { get; set; }
        public Aed Srd { get; set; }
        public Aed Thb { get; set; }
        public Aed Tvd { get; set; }
        public Aed Kpw { get; set; }
        public Aed Yer { get; set; }
        public Aed Amd { get; set; }
        public Aed Pkr { get; set; }
        public Aed Mwk { get; set; }
        public Aed Php { get; set; }
        public Aed Czk { get; set; }
        public Aed Mmk { get; set; }
        public Aed Ron { get; set; }
        public Aed Dop { get; set; }
        public Aed Ghs { get; set; }
        public Aed Try { get; set; }
        public Aed Egp { get; set; }
        public Aed Mzn { get; set; }
        public Aed Huf { get; set; }
        public Aed Aed { get; set; }
        public Aed All { get; set; }
        public Aed Fjd { get; set; }
        public Aed Mdl { get; set; }
        public Aed Byn { get; set; }
        public Aed Lkr { get; set; }
        public Aed Bmd { get; set; }
        public Aed Nio { get; set; }
        public Aed Sos { get; set; }
        public Aed Jod { get; set; }
        public Aed Tmt { get; set; }
        public Aed Crc { get; set; }
        public Aed Vnd { get; set; }
        public Aed Szl { get; set; }
        public Aed Zmw { get; set; }
        public Aed Chf { get; set; }
        public Aed Uzs { get; set; }
        public Aed Awg { get; set; }
        public Aed Jpy { get; set; }
        public Aed Cve { get; set; }
        public Aed Hkd { get; set; }
        public Aed Bgn { get; set; }
        public Aed Lak { get; set; }
        public Aed Krw { get; set; }
        public Aed Tnd { get; set; }
        public Aed Zwl { get; set; }
        public Aed Mvr { get; set; }
        public Aed Sgd { get; set; }
        public Aed Aoa { get; set; }
        public Aed Myr { get; set; }
        public Aed Gnf { get; set; }
        public Aed Lyd { get; set; }
        public Aed Idr { get; set; }
        public Aed Scr { get; set; }
        public Aed Bnd { get; set; }
        public Aed Mxn { get; set; }
        public Aed Sll { get; set; }
        public Aed Cop { get; set; }
        public Aed Pgk { get; set; }
        public Aed Fkp { get; set; }
        public Aed Tzs { get; set; }
    }
}

